### ISSUE TITLE
SyntaxError in JSON

### ISSUE THREAD

**Issue by I4T2B** [bogenpirat/MMM-WetterOnline#1]
This Module won't work anymore.
The Logs shows:
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/opt/magic_mirror/modules/MMM-WetterOnline/node_helper.js:61:24)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Can anyone say what's wrong?

**Comment by bogenpirat** [comment]
currently works fine for me. do you have any more information, e.g. MagicMirror version or what your config looks like?

**Comment by I4T2B** [comment]
Now, it works also fine for me. May have been an error by WetterOnline. Thx for the fast reply.
