### ISSUE TITLE
Another Issue: TypeError

### ISSUE THREAD

**Issue by I4T2B** [bogenpirat/MMM-WetterOnline#2]
Error-Log:
[18.08.2021 16:56.22.537] [ERROR] Whoops! There was an uncaught exception...
[18.08.2021 16:56.22.552] [ERROR] TypeError: Cannot read property 'text' of null
at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-WetterOnline/node_helper.js:30:55)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1220:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
[18.08.2021 16:56.22.554] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

I tried with many citys but no one works for me. Log-Output was with muenchen.
Maybe anything changed by WetterOnline?

**Comment by bogenpirat** [comment]
you're right, the module seems to be broken right now. i'll take a look at it soon.

**Comment by bogenpirat** [comment]
fixed in 20aa882. WO obviously changed their markup and moved around a bunch of data payloads. the current conditions verbiage may have changed, and unfortunately the wind description text doesn't make as much sense anymore. to be fair, it doesn't on the WO site either.

i switched from node-html-parser to cheerio as a dependency, so you'll need to go to the module directory, do `git pull` followed by `npm i` to get a hold of that (just like when you first installed it).

should be displaying fine after a restart without any additional changes on the user's end. let me know here if not.

**Comment by I4T2B** [comment]
Thanks, now all works fine.
